"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my honor, Mark Fakhoury, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: mwf634
UT EID 2:
"""


def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    rails = [""] * key

    rail = 0
    direction = -1

    for char in string:
        rails[rail] += char
        if rail in (0, key -1):
            direction *= -1
        rail += direction
    return "".join(rails)

def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    pattern = [0] * len(string)

    rail = 0
    direction = -1

    for i in range(len(string)):
        pattern[i] = rail
        if rail in (0, key -1):
            direction *= -1
        rail += direction

    rail_counts = [0] * key
    for rail_index in pattern:
        rail_counts[rail_index] += 1

    rails = []
    index = 0
    for count in rail_counts:
        rails.append(string[index: index + count])
        index += count

    rail_pointers = [0] * key
    decoded = ""

    for rail_index in pattern:
        decoded += rails[rail_index][rail_pointers[rail_index]]
        rail_pointers[rail_index] += 1

    return decoded


def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    result = ""
    for char in string:
        if char.isalpha():
            result += char.lower()
    return result 
def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    p_index = ord(p) - ord("a")
    s_index = ord(s) - ord("a")
    encoded = (s_index + p_index) % 26

    return chr(encoded + ord("a"))

def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    p_index = ord(p) - ord("a")
    s_index = ord(s) - ord("a")
    decoded = (s_index - p_index + 26) % 26

    return chr(decoded + ord("a"))


def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    string = filter_string(string)
    phrase = filter_string(phrase)
    result = ""
    for i, s_char in enumerate(string):
        p_char = phrase[i % len(phrase)]
        result += encode_character(p_char, s_char)
    return result

def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    string = filter_string(string)
    phrase = filter_string(phrase)
    result = ""

    for i, s_char in enumerate(string):
        p_char = phrase[i % len(phrase)]
        result += decode_character(p_char, s_char)

    return result

def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # encrypt and print the encoded text using rail fence cipher

    # read encoded text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # decrypt and print the plain text using rail fence cipher

    # read the plain text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # encrypt and print the encoded text using Vigenere cipher

    # read the encoded text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # decrypt and print the plain text using Vigenere cipher
    print("Rail Fence Cipher\n")

    print("Plain Text:", end="")
    plain_text_rf = input().strip()
    print("Key:", end="")
    key_rf =int(input())
    encoded_rf = rail_fence_encode(plain_text_rf, key_rf)
    print(f"Encoded Text:{encoded_rf}")
    print()
    
    print("Encoded Text:", end="")
    encoded_text_rf = input().strip()
    print("Key:", end="")
    decode_key_rf = int(input())
    decoded_rf = rail_fence_decode(encoded_text_rf, decode_key_rf)
    print(f"Decoded Text:{decoded_rf}")
    print()

    print("Vigenere Cipher\n")

    print("Plain Text:", end="")
    plain_text_v = input().strip()
    print("Pass Phrase:", end="")
    encode_phrase = input().strip()
    #filtered_plain = filter_string(plain_text_v)
    #filtered_phrase = filter_string(encode_phrase)
    encoded_v = vigenere_encode(plain_text_v, encode_phrase)
    print(f"Encoded Text:{encoded_v}")
    print()

    print("Encoded Text:", end="")
    encoded_text_v = input().strip()
    print("Pass Phrase:", end="")
    decode_phrase = input().strip()
    #filtered_pass = filter_string(decode_phrase)
    decoded_v = vigenere_decode(encoded_text_v, decode_phrase)
    print(f"Decoded Text:{decoded_v}")


# Do NOT modify the following code.
if __name__ == "__main__":
    main()
